authorization/BUILD.bazel, authz/BUILD.bazel, cert/BUILD.bazel, console/BUILD.bazel, pathz/BUILD.bazel, pathz/pathz.proto, ssh/BUILD.bazel
Pathz improvements
* Changes name of `PathzManagement` service name to `Pathz`
* Adds `Probe()` RPC to check if an operation is permitted for a specified user
* The policy field now has to be of `gnsi.authorization.AuthorizationPolicy` type
=> Pathz improvements

authorization/README.md, authorization/authorization.proto, authorization/index.md
Offline discussions lead to some cleanup and conformal coating of the proto/documentation.
Effectively attempt to get the language/usage in line with gNMI normsl
=> Change the authorization proto and associated documentation

.github/linters/.yaml-lint.yml, .github/workflows/linter.yml, README.md, cert/index.md, pathz/README.md, pathz/gnsi-pathz.html, pathz/gnsi-pathz.yang, pathz/pathz.proto
* Removes Install()
* Adds Get()
* Adds PolicyInstance enum and adds its use to Probe() and Get()
* Removes 'Pathz' from RotatePathz{Request|Response}
=> Removing unbounded collection of pathz policies. Now active + sandbox pathz policies only.

pathz/README.md, pathz/gnsi-pathz.html, pathz/gnsi-pathz.yang
Replaced ID with type of instance (ACTIVE or SANDBOX) in descriptions.
=> Fixes wording in description of pathz policy identifier.

authz/README.md
Clarify that the name field in the Rule message should be unique.
As defined in
https://github.com/grpc/proposal/blob/master/A43-grpc-authorization-api.md#proposal
=> authz: clarify Rule name field in README

.bazelrc, WORKSPACE
bazel 6.0.0 introduced a change which is backward incompatible, see: https://github.com/bazelbuild/bazel/issues/8622
The upb package (@upb) which is a dependancy for rules_proto_grpc (@rules_proto_grpc) had lines in its build which were targeting @bazel_tools//platforms:windows, which had been removed. This made it impossible to build on bazel 6.0.0.
Update the rules_proto_grpc to 4.3.0 to resolve this.
Building with the updated version of rules_proto_grpc would then fail because @com_github_grpc_grpc required c++14 in lots of files. Example error:
external/com_github_grpc_grpc/src/core/lib/gpr/useful.h:109:17: error: use of 'auto' in lambda parameter declaration only available with '-std=c++14' or '-std=gnu++14'
Add a .bazelrc file to force c++14 when building.
Also bump the version of …
=> bazel: fix for bazel 6.0.0

credentialz/README.md, credentialz/credentialz.proto, version/version.proto
Allowed authentication types can be set globally for sshd. After renaming RotateHostCredentials to RotateHostParameters this PR adds a request/response type for setting a repeated AllowedAuthentication enum. See `man 5 sshd_config` for details on allowable authentication mechanisms.
=> Rename RotateHostCredentials to RotateHostParameters, Add AllowedAuthentication setting

accounting/acct.proto
accounting.CommandService.cmd{_args} and
accounting.GrpcService.{payloads,config_metadata} to indicate that the fields were truncates due to implementation limitations.
fixes #96
=> Add boolean *_istrunctated fields corresponding to

authz/README.md, authz/authz.proto
In particular, update the proto comments to require devices preserve the version and created_on across cold-starts/reboot, as in the README, which I presume was the intent.
=> Clean-up some language, omissions, and inconsistencies.

authz/README.md, authz/authz.proto
has been set, not permit a vendor to choose the default policy. Implementations should be consistent.
fixes opensconfig/grpc#99
=> The default authz policy should allow all RPCs by default until a policy

certz/certz.proto, credentialz/credentialz.proto, pathz/pathz.proto
GC duplicated text about created_on timestamp source. As in MR#101, version and created_on values must be preserved; use the same text in all instances.
=> "switch" -> "device"

acctz/acctz.proto
Also, add a boolean allowing the server to indicate that the record history has been truncated relative to the requested reference timestamp.
=> Add comments to clarify the record history on a server.

certz/README.md, certz/gnsi-certz.html, certz/gnsi-certz.yang
This leaf creates an association between a particular gRPC server and the ID of the SSL profile that it is running with.
see https://github.com/openconfig/gnsi/issues/111
=> certz: add ssl-profile-id leaf

credentialz/gnsi-credentialz.yang
Fixed the order of `config` statement according to RFC 6020, Section 12
=> Fix the canonical order of "config" statement

credentialz/credentialz.proto
Add comments to the proto file which specifies how to clear the configured authorized keys/principals from configuration.
=> Provision for clearing SSH authorized keys/principals from configuration

acctz/acctz.proto
SessionInfo.
Add a tty field to SessionInfo for the tty/vty; eg: con0, aux0. Add a session status field to SessionInfo to track login/out (aka start/stop records) and requests that are altogether a login, process request, logout events.
Add a AuthorDetail field to RecordResponse for the authorization of a request.
=> separate authentication status and user info.  Make both members of

authz/README.md
Simple import error from this module's origin.
=> README references the wrong yang filename

acctz/README.md, acctz/gnsi-acctz.yang
Not sure if I amended the correct spot in the tree, but this is a starting point for discussion related to #97.  Hoping for some discussion or better solutions.
=> Initial stab at telemetry for accounting

credentialz/gnsi-credentialz.yang
Incremented the revision due to the change in leaf names in [this](https://github.com/openconfig/gnsi/commit/241b10833884ad01fb04e08023b6d5507566e10a). This also fixes a typo in a leaf name.
=> Fix typo in the YANG leaf name

acctz/README.md, acctz/acctz.proto
removing the keepalive concept and mentioning the behavior the server can adopt to timeout a dead client.
Addresses issue #137
=> Update docs & comments for the behavior of the RecordSubscribe service,

certz/gnsi-certz.html, certz/gnsi-certz.yang
`connection-rejects` should increment for failed
connection attempts
YANG descriptions should have semicolons at the end
=> gnsi/certz: fix error in yang description

certz/README.md, certz/certz.proto
expectation that only new profiles will be created to use other certs
=> Update readme to use agreed upon profile name and clarify the

pathz/index.md
The index.md is updated with a section covering the expected behaviour for ongoing subscriptions when a server
experiences a pathz policy change.
This commit also updates the pathz.UploadResponse value so that
it contains information about ongoing subscriptions and whether
they would experience different behaviour under the incoming policy. .pb.go files were regenerated.
=> gnsi/pathz: clarify rotation behaviour for ongoing gNMI subscriptions

acctz/acctz.proto
Provide clarification on the field `component_name`.
=> Provide clarification on the field component_name

certz/README.md, certz/certz.proto
clarify that we should return an error if the
entity_type field matches the type of an entity already
being rotated in the same UploadRequest.
I.e. the artifact being rotated should either be uploaded in
the UploadRequest _or_ it should be copied from an
existing ssl profile, but not both.
=> certz: clarify usage of entity_type field

acctz/acctz.proto
`history_istruncated` in a RecordResponse is set to True if the gnsi.acctz server senses that there might be some events which have occurred prior to the timestamp in the RecordResponse message for which it might be missing RecordResponses. This helps the gnsi.acctz client to stitch a timeline where it can detect potential gaps in the timeline.
=> Add detailed scenarios on when history_istruncated is set to True

pathz/BUILD.bazel
Adds a default build rule for pathz to mirror the behavior of other protos
=> Default go build rule in pathz

certz/certz.pb.go, certz/certz.proto
```
* (M) certz/certz.proto
- trust_bundle_pcks7 --> trust_bundle_pkcs7 in the entity oneof.
```
This looks like a typo -- not sure if this field has been used, if so
we should probably either mark this as a known error and continue along
our merry way, or determine whether we think there are any textprotos on
disk anywhere that would mean that we need to mark field 8 as deprecated.
=> Fix typo in `certz.proto`.

certz/certz.proto
This will be a bundle of certificates, not public keys
=> certz: clarify comment for TrustBundle.pkcs7_block field

certz/README.md, certz/certz.proto
The ssl_profile_id field should always be set,
and providing an empty ssl_profile_id to the server should result in an error being returned.
=> certz: clarify that ssl_profile_id cannot be empty

certz/certz.proto
```
* (M) certz/certz.proto
- It is possible within the current certz API for a client to start
an operation for ssl_profile_id = "foo" and then, using the same
RPC, start an operation for ssl_profile_id = "bar". This
introduces significant server-side complexity since it must track
the state machine on a per-profile basis, with little benefit to
the client. Clarify that this is not allowed and specify the
error code to indicate as such.
```
=> Clarify multiplexing profile operations is not allowed in Certz.Rotate

credentialz/credentialz.proto
The bit size were not supported in the current proto.  #205 
I think we should support these bit size as well
=> Added support for rsa 3072 and ecdsa 384

credentialz/credentialz.proto
Update the docuemntation for AccountCredential to make it clear what the parts of the proto message mean, with respect to a normal openssh format ssh public key.
=> Issue210: Update / Improve comment for 'AccountCredentials'.

certz/README.md, certz/certz.proto
This structure is created by TPM2_CreatePrimary(), and provides information relating to the creation environment for the AK, such as the parent name. Exposing this allows verifiers to check that appropriate values were set.
=> Add TPM2B_CREATION_DATA to the MBM data.

.github/workflows/bazel.yml, .github/workflows/linter.yml
Pin Github Actions to [specific commit hashes](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) instead of tags.
setup-bazelisk action is removed because it is not needed; bazelisk is included in the base runner image.
=> Pin GitHub Actions to specific commits
